version: '3.8'

services:
  # Backend API Service
  backend:
    build:
      context: ./backend
      dockerfile: MedicalAppointmentApi/Dockerfile
    container_name: medical-appointment-api
    ports:
      - "5236:80"
    environment:
      - ASPNETCORE_ENVIRONMENT=Production
      - Supabase__Url=${SUPABASE_URL}
      - Supabase__Key=${SUPABASE_KEY}
      - ConnectionStrings__Supabase=${SUPABASE_CONNECTION_STRING}
      - AllowedOrigins=http://localhost:4200,http://frontend:80
    networks:
      - medical-app-network
    healthcheck:
      test: ["CMD-SHELL", "curl -f http://localhost:80/health || exit 1"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s
    restart: unless-stopped

  # Frontend Angular Service
  frontend:
    build:
      context: ./frontend/medical-appointment-app
      dockerfile: Dockerfile
    container_name: medical-appointment-frontend
    ports:
      - "4200:80"
    depends_on:
      backend:
        condition: service_healthy
    networks:
      - medical-app-network
    environment:
      - API_URL=http://backend:80/api
    restart: unless-stopped

networks:
  medical-app-network:
    driver: bridge
